- hosts: myservers
  become: true
  vars:
      db_user: "db_user"
      db_password: "db_password"
      db_name: "db_name"
  roles:
    - distribution
    - packages
    - php
    - apache
    - mariaDB
    - composer
    - firewall
    - application 
    - tailwind
    - images
    - restart


  